# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 19:19
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('view', models.CharField(max_length=200)),
                ('Discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photid', models.CharField(max_length=200)),
                ('postdate', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followingId', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shotname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberId', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Privacy', models.CharField(max_length=200)),
                ('UploaadDate', models.CharField(max_length=200)),
                ('view', models.CharField(max_length=200)),
                ('songs', models.CharField(max_length=200, null=True)),
                ('imagepathe', models.FileField(blank=True, null=True, upload_to='')),
                ('Album', models.ManyToManyField(to='media.Album')),
                ('location', models.ManyToManyField(to='media.location')),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tag_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoID', models.CharField(max_length=200)),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.tag')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25, null=True)),
                ('lastname', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile', models.ImageField(null=True, upload_to='images/')),
                ('curentus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTofollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('following', models.ManyToManyField(to='media.following')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ManyToManyField(to='media.user'),
        ),
        migrations.AddField(
            model_name='following',
            name='use_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ManyToManyField(to='media.photo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='tag',
            field=models.ManyToManyField(to='media.tag'),
        ),
    ]
