# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 16:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumID', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('LocationId', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('MemberId', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Privacy', models.CharField(max_length=200)),
                ('UploaadDate', models.CharField(max_length=200)),
                ('view', models.CharField(max_length=200)),
                ('imagepathe', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='tag_photo',
            name='tagId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.tag'),
        ),
    ]
