# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20190325_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='songs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='imagepathe',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
